module.exports = [
  {
    name: 'Arizona Cardinals',
    nickname: 'Cardinals',
    city: 'Arizona',
    abbreviation: 'ARI',
  },
  {
    name: 'Atlanta Falcons',
    nickname: 'Falcons',
    city: 'Atlanta',
    abbreviation: 'ATL',
  },
  {
    name: 'Baltimore Ravens',
    nickname: 'Ravens',
    city: 'Baltimore',
    abbreviation: 'BAL',
  },
  {
    name: 'Buffalo Bills',
    nickname: 'Bills',
    city: 'Buffalo',
    abbreviation: 'BUF',
  },
  {
    name: 'Carolina Panthers',
    nickname: 'Panthers',
    city: 'Carolina',
    abbreviation: 'CAR',
  },
  {
    name: 'Chicago Bears',
    nickname: 'Bears',
    city: 'Chicago',
    abbreviation: 'CHI',
  },
  {
    name: 'Cincinnati Bengals',
    nickname: 'Bengals',
    city: 'Cincinnati',
    abbreviation: 'CIN',
  },
  {
    name: 'Cleveland Browns',
    nickname: 'Browns',
    city: 'Cleveland',
    abbreviation: 'CLE',
  },
  {
    name: 'Dallas Cowboys',
    nickname: 'Cowboys',
    city: 'Dallas',
    abbreviation: 'DAL',
  },
  {
    name: 'Denver Broncos',
    nickname: 'Broncos',
    city: 'Denver',
    abbreviation: 'DEN',
  },
  {
    name: 'Detroit Lions',
    nickname: 'Lions',
    city: 'Detroit',
    abbreviation: 'DET',
  },
  {
    name: 'Green Bay Packers',
    nickname: 'Packers',
    city: 'Green Bay',
    abbreviation: 'GB',
  },
  {
    name: 'Houston Texans',
    nickname: 'Texans',
    city: 'Houston',
    abbreviation: 'HOU',
  },
  {
    name: 'Indianapolis Colts',
    nickname: 'Colts',
    city: 'Indianapolis',
    abbreviation: 'IND',
  },
  {
    name: 'Jacksonville Jaguars',
    nickname: 'Jaguars',
    city: 'Jacksonville',
    abbreviation: 'JAX',
  },
  {
    name: 'Kansas City Chiefs',
    nickname: 'Chiefs',
    city: 'Kansas City',
    abbreviation: 'KC',
  },
  {
    name: 'Las Vegas Raiders',
    nickname: 'Raiders',
    city: 'Las Vegas',
    abbreviation: 'LV',
  },
  {
    name: 'Los Angeles Chargers',
    nickname: 'Chargers',
    city: 'Los Angeles',
    abbreviation: 'LAC',
  },
  {
    name: 'Los Angeles Rams',
    nickname: 'Rams',
    city: 'Los Angeles',
    abbreviation: 'LAR',
  },
  {
    name: 'Miami Dolphins',
    nickname: 'Dolphins',
    city: 'Miami',
    abbreviation: 'MIA',
  },
  {
    name: 'Minnesota Vikings',
    nickname: 'Vikings',
    city: 'Minnesota',
    abbreviation: 'MIN',
  },
  {
    name: 'New England Patriots',
    nickname: 'Patriots',
    city: 'New England',
    abbreviation: 'NE',
  },
  {
    name: 'New Orleans Saints',
    nickname: 'Saints',
    city: 'New Orleans',
    abbreviation: 'NO',
  },
  {
    name: 'New York Giants',
    nickname: 'Giants',
    city: 'New York',
    abbreviation: 'NYG',
  },
  {
    name: 'New York Jets',
    nickname: 'Jets',
    city: 'New York',
    abbreviation: 'NYJ',
  },
  {
    name: 'Philadelphia Eagles',
    nickname: 'Eagles',
    city: 'Philadelphia',
    abbreviation: 'PHI',
  },
  {
    name: 'Pittsburgh Steelers',
    nickname: 'Steelers',
    city: 'Pittsburgh',
    abbreviation: 'PIT',
  },
  {
    name: 'San Francisco 49ers',
    nickname: '49ers',
    city: 'San Francisco',
    abbreviation: 'SF',
  },
  {
    name: 'Seattle Seahawks',
    nickname: 'Seahawks',
    city: 'Seattle',
    abbreviation: 'SEA',
  },
  {
    name: 'Tampa Bay Buccaneers',
    nickname: 'Buccaneers',
    city: 'Tampa Bay',
    abbreviation: 'TB',
  },
  {
    name: 'Tennessee Titans',
    nickname: 'Titans',
    city: 'Tennessee',
    abbreviation: 'TEN',
  },
  {
    name: 'Washington Football Team',
    nickname: 'Football Team',
    city: 'Washington',
    abbreviation: 'WAS',
  },
];
