module.exports = [
  'Dallas Cowboys',
  'Tampa Bay Buccaneers',
  'Atlanta Falcons',
  'Philadelphia Eagles',
  'Buffalo Bills',
  'Pittsburgh Steelers',
  'Minnesota Vikings',
  'Cincinnati Bengals',
  'Detroit Lions',
  'San Franciso 49ers',
  'Tennessee Titans',
  'Arizona Cardinals',
  'Indianapolis Colts',
  'Seattle Seahawks',
  'Los Angeles Chargers',
  'Washington Football Team',
  'New York Jets',
  'Carolina Panthers',
  'Jacksonville Jaguars',
  'Houston Texans',
  'Cleveland Browns',
  'Kansas City Chiefs',
  'Miami Dolphins',
  'New England Patriots',
  'Green Bay Packers',
  'New Orleans Saints',
  'Denver Broncos',
  'New York Giants',
  'Chicago Bears',
  'Los Angeles Rams',
  'Las Vegas Raiders',
  'Baltimore Ravens',
];
